### ISSUE TITLE
mpl, эпизод 2 : переносимость кода

### ISSUE THREAD

**Issue by avasyukov** [Plakhotniuk/Python3Sem#1]
(Этого не было в материалах. И это почти офтоп. Но тем не менее.)

Вот эта строчка:
https://github.com/Plakhotniuk/Python3Sem/blob/8d0b681a7326ef3ffbca63dddff192f4fc983bb8/Lab_1_MatplotLib/Episode2/Episode2.py#L8
внезапно не переносима между разными операционными системами.

Потому что разделитель элементов пути по ФС разный в разных ОС. Идейно верно склеить кусочки пути (имя папки и имя файла) с помощью `os.path.join`.

(И ниже по коду ещё раз аналогично.)

**Comment by Plakhotniuk** [comment]
Писал этот код несколько недель назад, все работало. Сейчас запускаю, выдает ошибку. Очень странное дело.  Даже с использованием os.path.join пишет: No such file or directory. Убрал Episode2/ - все опять заработало нормально. Как такое возможно, я не знаю.

**Comment by avasyukov** [comment]
Думаю, дело в том, откуда запускается скрипт, и где лежат файлики. Например, `os.path.join('Episode2', 'graphics.gif')` говорит "из *текущей* директории перейти вниз в Episode2, в ней найти файл graphics.gif".
