### ISSUE TITLE
mpl, эпизод 3 : выборки pandas-ом

### ISSUE THREAD

**Issue by avasyukov** [Plakhotniuk/Python3Sem#4]
Сам по себе pandas - ок и разрешён. Но если уж начали решать с ним, pandas-код пишем красивый.

Вот эти две выборки корректны, но неэффективны:
https://github.com/Plakhotniuk/Python3Sem/blob/8d0b681a7326ef3ffbca63dddff192f4fc983bb8/Lab_1_MatplotLib/Episode3/Episode3.py#L10

https://github.com/Plakhotniuk/Python3Sem/blob/8d0b681a7326ef3ffbca63dddff192f4fc983bb8/Lab_1_MatplotLib/Episode3/Episode3.py#L15

Их нужно привести в чувство.

**Comment by avasyukov** [comment]
Стало резко лучше. Для препов осталось `data.loc[data['Preps'] == i]['Marks']`превратить в `data.loc[data['Preps'] == i, 'Marks']` (тонкий момент, совсем не про эту лабу, но раз уж начали). Ну и для групп аналогично поправить.

**Comment by Plakhotniuk** [comment]
Вроде всё поправил

**Comment by avasyukov** [comment]
Подтверждаю, стало ок. Для групп выборка с `==` была бы более фэншуйна, чем `isin` (там же проверка на равенство по сути), но это уже совсем мелочи, можно не править.
