### ISSUE TITLE
numpy, эпизод 1 : диапазон

### ISSUE THREAD

**Issue by avasyukov** [Plakhotniuk/Python3Sem#8]
Кажется, нижнюю часть диапазона не дотянули до нуля:
https://github.com/Plakhotniuk/Python3Sem/blob/45b8d62824125e59fe8787def7bbb757e4fe9f5a/Lab_3_NumPy/Episode1/Episode1.py#L6-L7

**Comment by Plakhotniuk** [comment]
Поправил issue по пандасам, также поправил диапазон здесь
