### ISSUE TITLE
numpy. эпизод 2 : скорость работы

### ISSUE THREAD

**Issue by avasyukov** [Plakhotniuk/Python3Sem#9]
Это разумная формула:
https://github.com/Plakhotniuk/Python3Sem/blob/45b8d62824125e59fe8787def7bbb757e4fe9f5a/Lab_3_NumPy/Episode2/Task.py#L6

Но от for-ов придётся всё же избавиться, по крайней мере для основной части массива.

Можно посмотреть на `cumsum` или `convolve`. Можно прикрутить магию слайсов такого духа:
```
# это не логика из задачи, просто техническая демка, что можно делать со слайсами
z = np.arange(10)
z[:-1] = z[:-1] + z[1:]
print(z)
```

**Comment by Plakhotniuk** [comment]
Оптимизировал работу. До конца от for избавиться не удалось, но ускорить существенно получилось. Сравнил среднее время работы. На 100 элементах получается в 2 раза примерно, а если элементов 400, то уже на порядок выигрывает consolve

**Comment by avasyukov** [comment]
Реализация ок. _(А если элементов станет 10 000, то разница будет ещё заметнее.)_
